In [2]:
#import libraries
import pandas as pd
import io
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [4]:
df=pd.read_csv("Churn_Modelling.csv",index_col="RowNumber")
df.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
RowNumber,,,,,,,,,,,,,
1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
# Finding Missing Values
df.isnull().sum()

CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [8]:
#Check for Duplicates
df.duplicated().sum()

0

In [ ]:
#Detect Outliers

In [9]:
df.describe()

,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [10]:
df = df.drop(['Surname', 'Geography', 'Gender'], axis=1)

In [11]:
scaler = MinMaxScaler()
df1 = pd.DataFrame(scaler.fit_transform(df))
print(df1)

             0      1         2    3         4         5    6    7         8  \
0     0.275616  0.538  0.324324  0.2  0.000000  0.000000  1.0  1.0  0.506735
1     0.326454  0.516  0.310811  0.1  0.334031  0.000000  0.0  1.0  0.562709
2     0.214421  0.304  0.324324  0.8  0.636357  0.666667  1.0  0.0  0.569654
3     0.542636  0.698  0.283784  0.1  0.000000  0.333333  0.0  0.0  0.469120
4     0.688778  1.000  0.337838  0.2  0.500246  0.000000  1.0  1.0  0.395400
...        ...    ...       ...  ...       ...       ...  ...  ...       ...
9995  0.162119  0.842  0.283784  0.5  0.000000  0.333333  1.0  0.0  0.481341
9996  0.016765  0.332  0.229730  1.0  0.228657  0.000000  1.0  1.0  0.508490
9997  0.075327  0.718  0.243243  0.7  0.000000  0.000000  0.0  1.0  0.210390
9998  0.466637  0.844  0.324324  0.3  0.299226  0.333333  1.0  0.0  0.464429
9999  0.250483  0.884  0.135135  0.4  0.518708  0.000000  1.0  0.0  0.190914

        9
0     1.0
1     0.0
2     1.0
3     0.0
4     0.0
...   ...
9995  0.0
9996  0.0
9997  1.0
9998  1.0
9999  0.0

[10000 rows x 10 columns]

In [13]:
x = df.iloc[:, :-1].values

In [14]:
x

array([[1.5634602e+07, 6.1900000e+02, 4.2000000e+01, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [1.5647311e+07, 6.0800000e+02, 4.1000000e+01, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.5619304e+07, 5.0200000e+02, 4.2000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.5584532e+07, 7.0900000e+02, 3.6000000e+01, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.5682355e+07, 7.7200000e+02, 4.2000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.5628319e+07, 7.9200000e+02, 2.8000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [15]:
y = df.iloc[:, -1].values
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [18]:
print(x_train)
print(len(x_train))

[[1.5627995e+07 7.5600000e+02 2.6000000e+01 ... 0.0000000e+00
  1.0000000e+00 1.3503457e+05]
 [1.5641850e+07 7.1700000e+02 4.0000000e+01 ... 1.0000000e+00
  0.0000000e+00 1.1088714e+05]
 [1.5705009e+07 6.4900000e+02 5.6000000e+01 ... 1.0000000e+00
  0.0000000e+00 8.9405260e+04]
 ...
 [1.5711618e+07 7.0400000e+02 3.9000000e+01 ... 1.0000000e+00
  0.0000000e+00 1.1651112e+05]
 [1.5809057e+07 6.0000000e+02 2.7000000e+01 ... 1.0000000e+00
  1.0000000e+00 1.7203122e+05]
 [1.5782875e+07 6.6300000e+02 3.3000000e+01 ... 1.0000000e+00
  1.0000000e+00 2.8531810e+04]]
8000

In [19]:
print(x_test)
print(len(x_test))

[[1.5745605e+07 7.2200000e+02 4.7000000e+01 ... 1.0000000e+00
  1.0000000e+00 9.0655940e+04]
 [1.5716491e+07 7.1000000e+02 5.1000000e+01 ... 0.0000000e+00
  1.0000000e+00 1.4140051e+05]
 [1.5582404e+07 5.7200000e+02 2.6000000e+01 ... 1.0000000e+00
  0.0000000e+00 1.1938141e+05]
 ...
 [1.5750803e+07 6.9300000e+02 3.0000000e+01 ... 1.0000000e+00
  1.0000000e+00 5.0457200e+04]
 [1.5695339e+07 5.1700000e+02 5.3000000e+01 ... 1.0000000e+00
  0.0000000e+00 5.4676100e+04]
 [1.5702601e+07 6.8000000e+02 3.0000000e+01 ... 0.0000000e+00
  1.0000000e+00 4.4384570e+04]]
2000